version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysqlaya
    command: mysqld --default-authentication-plugin=mysql_native_password
 
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    volumes:
      - db:/var/lib/mysql
      - mysql-data:/var/local/mysql/data
  app_maven:
    depends_on:
      - mysqldb
    image: ayaajmi/achat
    container_name: ayaajmi
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" 
        }'
    volumes:
      - .m2:/root/.m2
volumes: 
      db:
      mysql-data:   
