version: "3"
services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
      #MYSQL_USER: achat_user
      #MYSQL_PASSWORD:
    #volumes:
      #- mysql_database:/var/lib/mysql
  spring-boot:
    depends_on:
      - database
    image: arijboudhina/achat
    restart: always
    ports:
      - 8089:8089
    container_name: achat